/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package uk.org.lidalia.gradle.plugin.downloaddependencies

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'uk.org.lidalia.gradle.plugin.downloaddependencies.greeting' plugin.
 */
class LidaliaDownloadDependenciesPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("uk.org.lidalia.gradle.plugin.downloaddependencies.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
