/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package uk.org.lidalia.gradle.plugin.downloaddependencies

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldNotBe
import org.gradle.testfixtures.ProjectBuilder

/**
 * A simple unit test for the 'uk.org.lidalia.downloaddependencies' plugin.
 */
class LidaliaDownloadDependenciesPluginTest : StringSpec({
    "plugin registers task" {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("uk.org.lidalia.downloaddependencies")

        // Verify the result
        project.tasks.findByName("downloadDependencies") shouldNotBe null
    }
})
